version: '3'
services:
  app:

    build:
      context: .
      dockerfile: ./Dockerfile.node
    ports:
      - "22922:3000"  # Maps the container port 3000 to external port 6622.
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
  mongo:
    image: mongo
    #ports:
    #  - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
